// crates/core/src/commands/group_commands.rs
// The Command trait's description() returns &str (not &'static str) because
// CompoundCommand borrows from its String field. Literal returns in other impls
// trigger this lint unnecessarily.
#![allow(clippy::unnecessary_literal_bound)]

use std::cell::RefCell;

use crate::command::{Command, SideEffect};
use crate::commands::style_commands::validate_transform;
use crate::document::Document;
use crate::error::CoreError;
use crate::id::NodeId;
use crate::node::{Node, NodeKind, Transform};
use crate::tree;
use crate::validate::{MIN_GROUP_MEMBERS, validate_node_name};
use uuid::Uuid;

/// Records the original index of a child node in its parent's children list,
/// captured during `GroupNodes::apply` for use in undo to restore ordering.
#[derive(Debug, Clone)]
struct ChildOriginalIndex {
    node_id: NodeId,
    index: usize,
}

/// Groups multiple nodes under a new Group node.
///
/// The group's transform is the union bounding box of all selected nodes.
/// Children's coordinates are adjusted to be group-relative.
/// Requires 2+ nodes. All nodes must exist and share the same parent
/// (for the initial implementation; LCA support is deferred).
#[derive(Debug)]
pub struct GroupNodes {
    /// The node IDs to group.
    node_ids: Vec<NodeId>,
    /// The display name for the group node.
    group_name: String,
    /// UUID for the new group node (generated by caller).
    group_uuid: Uuid,
    /// Original indices of children in parent's children list, captured during
    /// apply for use in undo to restore sibling ordering.
    original_child_indices: RefCell<Vec<ChildOriginalIndex>>,
}

impl GroupNodes {
    /// Creates a new `GroupNodes` command.
    ///
    /// # Errors
    /// Returns `CoreError::ValidationError` if:
    /// - The group name is invalid
    /// - Fewer than `MIN_GROUP_MEMBERS` node IDs are provided
    pub fn new(
        node_ids: Vec<NodeId>,
        group_name: String,
        group_uuid: Uuid,
    ) -> Result<Self, CoreError> {
        validate_node_name(&group_name)?;
        if node_ids.len() < MIN_GROUP_MEMBERS {
            return Err(CoreError::ValidationError(format!(
                "grouping requires at least {MIN_GROUP_MEMBERS} nodes, got {}",
                node_ids.len()
            )));
        }
        Ok(Self {
            node_ids,
            group_name,
            group_uuid,
            original_child_indices: RefCell::new(Vec::new()),
        })
    }

    /// Returns the node IDs to group.
    #[must_use]
    pub fn node_ids(&self) -> &[NodeId] {
        &self.node_ids
    }

    /// Returns the group UUID.
    #[must_use]
    pub fn group_uuid(&self) -> Uuid {
        self.group_uuid
    }

    /// Returns the group name.
    #[must_use]
    pub fn group_name(&self) -> &str {
        &self.group_name
    }
}

/// Computes the union bounding box of the given nodes.
fn compute_union_bounds(
    doc: &Document,
    node_ids: &[NodeId],
) -> Result<(f64, f64, f64, f64), CoreError> {
    let mut min_x = f64::INFINITY;
    let mut min_y = f64::INFINITY;
    let mut max_x = f64::NEG_INFINITY;
    let mut max_y = f64::NEG_INFINITY;

    for &nid in node_ids {
        let t = doc.arena.get(nid)?.transform;
        min_x = min_x.min(t.x);
        min_y = min_y.min(t.y);
        max_x = max_x.max(t.x + t.width);
        max_y = max_y.max(t.y + t.height);
    }

    Ok((min_x, min_y, max_x - min_x, max_y - min_y))
}

impl Command for GroupNodes {
    fn apply(&self, doc: &mut Document) -> Result<Vec<SideEffect>, CoreError> {
        // Validate minimum count
        if self.node_ids.len() < MIN_GROUP_MEMBERS {
            return Err(CoreError::ValidationError(format!(
                "grouping requires at least {MIN_GROUP_MEMBERS} nodes, got {}",
                self.node_ids.len()
            )));
        }

        // Pre-validate: all nodes exist, share the same parent, and have a parent (RF-020)
        for &nid in &self.node_ids {
            doc.arena.get(nid)?;
        }

        let first_parent = doc.arena.get(self.node_ids[0])?.parent;
        let first_parent = first_parent.ok_or_else(|| {
            CoreError::ValidationError("cannot group nodes without a parent".to_string())
        })?;

        for &nid in &self.node_ids[1..] {
            let parent = doc.arena.get(nid)?.parent;
            if parent != Some(first_parent) {
                return Err(CoreError::ValidationError(
                    "all nodes must share the same parent for grouping".to_string(),
                ));
            }
        }

        // Pre-validate: record original child indices in parent (RF-001)
        // and verify all children are actually in the parent's children list (RF-007)
        let parent_node = doc.arena.get(first_parent)?;
        let mut child_indices = Vec::with_capacity(self.node_ids.len());
        for &nid in &self.node_ids {
            let idx = parent_node
                .children
                .iter()
                .position(|&id| id == nid)
                .ok_or_else(|| {
                    CoreError::ValidationError(format!(
                        "node {nid:?} is not in parent's children list"
                    ))
                })?;
            child_indices.push(ChildOriginalIndex {
                node_id: nid,
                index: idx,
            });
        }
        *self.original_child_indices.borrow_mut() = child_indices;

        // Compute union bounding box
        let (bx, by, bw, bh) = compute_union_bounds(doc, &self.node_ids)?;
        let group_transform = Transform {
            x: bx,
            y: by,
            width: bw,
            height: bh,
            rotation: 0.0,
            scale_x: 1.0,
            scale_y: 1.0,
        };
        validate_transform(&group_transform)?;

        // Find the topmost (lowest index) selected node in the parent's children
        // to determine insertion position
        let parent = doc.arena.get(first_parent)?;
        let mut insertion_index = parent.children.len();
        for &nid in &self.node_ids {
            if let Some(pos) = parent.children.iter().position(|&id| id == nid) {
                insertion_index = insertion_index.min(pos);
            }
        }

        // Create group node
        let mut group_node = Node::new(
            NodeId::new(0, 0),
            self.group_uuid,
            NodeKind::Group,
            self.group_name.clone(),
        )?;
        group_node.transform = group_transform;
        let group_id = doc.arena.insert(group_node)?;

        // Place group under the shared parent at the topmost position
        tree::rearrange(&mut doc.arena, group_id, first_parent, insertion_index)?;

        // Reparent children into the group, adjusting transforms to group-relative
        for &nid in &self.node_ids {
            let old_transform = doc.arena.get(nid)?.transform;
            let new_transform = Transform {
                x: old_transform.x - bx,
                y: old_transform.y - by,
                ..old_transform
            };
            // Remove from old parent and add to group
            tree::remove_child(&mut doc.arena, nid)?;
            tree::add_child(&mut doc.arena, group_id, nid)?;
            doc.arena.get_mut(nid)?.transform = new_transform;
        }

        Ok(vec![])
    }

    fn undo(&self, doc: &mut Document) -> Result<Vec<SideEffect>, CoreError> {
        // Find the group node by UUID
        let group_id = doc
            .arena
            .id_by_uuid(&self.group_uuid)
            .ok_or(CoreError::ValidationError(format!(
                "cannot undo GroupNodes: group with uuid {} not found",
                self.group_uuid
            )))?;

        let group_transform = doc.arena.get(group_id)?.transform;
        let group_children: Vec<NodeId> = doc.arena.get(group_id)?.children.clone();
        let group_parent = doc.arena.get(group_id)?.parent;

        // RF-017: Validate restored transforms symmetrically
        for &child_id in &group_children {
            let child_transform = doc.arena.get(child_id)?.transform;
            let restored_transform = Transform {
                x: child_transform.x + group_transform.x,
                y: child_transform.y + group_transform.y,
                ..child_transform
            };
            validate_transform(&restored_transform)?;
        }

        // Detach children from the group (but don't attach to parent yet)
        // and restore their absolute coordinates.
        let mut restored_children: Vec<(NodeId, Transform)> =
            Vec::with_capacity(group_children.len());
        for &child_id in &group_children {
            let child_transform = doc.arena.get(child_id)?.transform;
            let restored_transform = Transform {
                x: child_transform.x + group_transform.x,
                y: child_transform.y + group_transform.y,
                ..child_transform
            };
            tree::remove_child(&mut doc.arena, child_id)?;
            doc.arena.get_mut(child_id)?.transform = restored_transform;
            restored_children.push((child_id, restored_transform));
        }

        // Remove the group node first, so it doesn't interfere with index-based rearrange
        tree::remove_child(&mut doc.arena, group_id)?;
        doc.arena.remove(group_id)?;

        // RF-001: Restore children at their original indices in the parent.
        let indices = self.original_child_indices.borrow();
        if let Some(parent_id) = group_parent {
            if indices.is_empty() {
                // Fallback: just add children to parent (shouldn't happen normally)
                for (child_id, _) in &restored_children {
                    tree::add_child(&mut doc.arena, parent_id, *child_id)?;
                }
            } else {
                // Sort by original index (ascending) and insert at those positions.
                let mut sorted_indices: Vec<&ChildOriginalIndex> = indices.iter().collect();
                sorted_indices.sort_by_key(|ci| ci.index);
                for ci in sorted_indices {
                    tree::rearrange(&mut doc.arena, ci.node_id, parent_id, ci.index)?;
                }
            }
        }

        Ok(vec![])
    }

    fn description(&self) -> &str {
        "Group nodes"
    }
}

/// Ungroups one or more group nodes, reparenting their children
/// back to the group's parent.
///
/// Children's coordinates are adjusted from group-relative back to
/// parent-relative (by adding the group's position).
#[derive(Debug)]
#[allow(clippy::struct_field_names)]
pub struct UngroupNodes {
    /// The group node IDs to ungroup.
    group_ids: Vec<NodeId>,
    /// UUIDs of the group nodes (for undo reconstruction).
    group_uuids: Vec<Uuid>,
    /// Captured group snapshots for undo. Populated automatically during `apply()`
    /// via interior mutability (RF-003).
    group_snapshots: RefCell<Vec<GroupSnapshot>>,
}

/// Snapshot of a group node captured before ungrouping, used for undo.
#[derive(Debug, Clone)]
pub struct GroupSnapshot {
    /// UUID of the group node.
    pub uuid: Uuid,
    /// Arena `NodeId` of the group (needed for `reinsert`).
    pub node_id: NodeId,
    /// Full clone of the group `Node`.
    pub node: Node,
    /// The group's parent (if any).
    pub parent_id: Option<NodeId>,
    /// The group's index within its parent's children list.
    pub index_in_parent: usize,
    /// Children node IDs in order, with their pre-ungroup (group-relative) transforms.
    pub children: Vec<(NodeId, Transform)>,
}

impl UngroupNodes {
    /// Creates a new `UngroupNodes` command.
    ///
    /// # Errors
    /// Returns `CoreError::ValidationError` if:
    /// - `group_ids` is empty
    /// - `group_ids` and `group_uuids` have different lengths
    pub fn new(group_ids: Vec<NodeId>, group_uuids: Vec<Uuid>) -> Result<Self, CoreError> {
        if group_ids.is_empty() {
            return Err(CoreError::ValidationError(
                "ungrouping requires at least 1 group node".to_string(),
            ));
        }
        if group_ids.len() != group_uuids.len() {
            return Err(CoreError::ValidationError(format!(
                "group_ids length ({}) must match group_uuids length ({})",
                group_ids.len(),
                group_uuids.len()
            )));
        }
        Ok(Self {
            group_ids,
            group_uuids,
            group_snapshots: RefCell::new(Vec::new()),
        })
    }

    /// Returns the group IDs.
    #[must_use]
    pub fn group_ids(&self) -> &[NodeId] {
        &self.group_ids
    }

    /// Returns the group UUIDs.
    #[must_use]
    pub fn group_uuids(&self) -> &[Uuid] {
        &self.group_uuids
    }
}

impl Command for UngroupNodes {
    fn apply(&self, doc: &mut Document) -> Result<Vec<SideEffect>, CoreError> {
        if self.group_ids.is_empty() {
            return Err(CoreError::ValidationError(
                "ungrouping requires at least 1 group node".to_string(),
            ));
        }

        // Pre-validate: all nodes exist and are Group kind (RF-007)
        for &gid in &self.group_ids {
            let node = doc.arena.get(gid)?;
            if !matches!(node.kind, NodeKind::Group) {
                return Err(CoreError::ValidationError(format!(
                    "node {gid:?} is not a group (kind: {:?})",
                    node.kind
                )));
            }
        }

        // RF-003: Capture snapshots inside apply before destroying groups
        let mut snapshots = Vec::with_capacity(self.group_ids.len());
        for &gid in &self.group_ids {
            let group = doc.arena.get(gid)?;
            let group_parent = group.parent;

            let children_with_transforms: Vec<(NodeId, Transform)> = group
                .children
                .iter()
                .map(|&cid| {
                    let t = doc.arena.get(cid).map(|n| n.transform);
                    t.map(|transform| (cid, transform))
                })
                .collect::<Result<Vec<_>, _>>()?;

            // RF-012: Replace .unwrap_or(0) with error
            let index_in_parent = if let Some(pid) = group_parent {
                doc.arena
                    .get(pid)?
                    .children
                    .iter()
                    .position(|&id| id == gid)
                    .ok_or_else(|| {
                        CoreError::ValidationError(
                            "group not found in parent's children list".to_string(),
                        )
                    })?
            } else {
                0
            };

            let group_uuid = doc.arena.uuid_of(gid)?;

            snapshots.push(GroupSnapshot {
                uuid: group_uuid,
                node_id: gid,
                node: group.clone(),
                parent_id: group_parent,
                index_in_parent,
                children: children_with_transforms,
            });
        }
        *self.group_snapshots.borrow_mut() = snapshots;

        // Process each group
        for &gid in &self.group_ids {
            let group = doc.arena.get(gid)?;
            let group_transform = group.transform;
            let group_parent = group.parent;
            let group_children: Vec<NodeId> = group.children.clone();

            // RF-012: Replace .unwrap_or(0) with error
            let group_index = if let Some(pid) = group_parent {
                doc.arena
                    .get(pid)?
                    .children
                    .iter()
                    .position(|&id| id == gid)
                    .ok_or_else(|| {
                        CoreError::ValidationError(
                            "group not found in parent's children list".to_string(),
                        )
                    })?
            } else {
                0
            };

            // Reparent each child to the group's parent, adjusting coords
            for (i, &child_id) in group_children.iter().enumerate() {
                let child_transform = doc.arena.get(child_id)?.transform;
                let restored = Transform {
                    x: child_transform.x + group_transform.x,
                    y: child_transform.y + group_transform.y,
                    ..child_transform
                };
                // RF-017: Validate restored transforms
                validate_transform(&restored)?;
                tree::remove_child(&mut doc.arena, child_id)?;
                if let Some(pid) = group_parent {
                    tree::rearrange(&mut doc.arena, child_id, pid, group_index + i)?;
                }
                doc.arena.get_mut(child_id)?.transform = restored;
            }

            // Remove the now-empty group
            tree::remove_child(&mut doc.arena, gid)?;
            doc.arena.remove(gid)?;
        }

        Ok(vec![])
    }

    fn undo(&self, doc: &mut Document) -> Result<Vec<SideEffect>, CoreError> {
        let snapshots = self.group_snapshots.borrow();

        // Validate snapshots are available
        if snapshots.is_empty() {
            return Err(CoreError::ValidationError(
                "cannot undo UngroupNodes: no snapshots captured".to_string(),
            ));
        }

        // Restore from snapshots in reverse order
        for snapshot in snapshots.iter().rev() {
            // Reinsert the group node at its original arena slot
            doc.arena
                .reinsert(snapshot.node_id, snapshot.node.clone())?;

            // Re-attach to parent
            if let Some(pid) = snapshot.parent_id {
                tree::rearrange(
                    &mut doc.arena,
                    snapshot.node_id,
                    pid,
                    snapshot.index_in_parent,
                )?;
            }

            // Reparent children back into the group, restoring group-relative coords
            for &(child_id, old_child_transform) in &snapshot.children {
                // RF-017: Validate restored transforms symmetrically
                validate_transform(&old_child_transform)?;
                tree::remove_child(&mut doc.arena, child_id)?;
                tree::add_child(&mut doc.arena, snapshot.node_id, child_id)?;
                doc.arena.get_mut(child_id)?.transform = old_child_transform;
            }
        }

        Ok(vec![])
    }

    fn description(&self) -> &str {
        "Ungroup nodes"
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::document::Document;
    use crate::node::{Node, NodeKind};
    use crate::tree;
    fn make_uuid(n: u8) -> Uuid {
        Uuid::from_bytes([n, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    }

    fn insert_rect(
        doc: &mut Document,
        n: u8,
        name: &str,
        x: f64,
        y: f64,
        w: f64,
        h: f64,
    ) -> NodeId {
        let mut node = Node::new(
            NodeId::new(0, 0),
            make_uuid(n),
            NodeKind::Rectangle {
                corner_radii: [0.0; 4],
            },
            name.to_string(),
        )
        .expect("create node");
        node.transform = Transform {
            x,
            y,
            width: w,
            height: h,
            rotation: 0.0,
            scale_x: 1.0,
            scale_y: 1.0,
        };
        doc.arena.insert(node).expect("insert")
    }

    fn insert_frame(doc: &mut Document, n: u8, name: &str) -> NodeId {
        let node = Node::new(
            NodeId::new(0, 0),
            make_uuid(n),
            NodeKind::Frame { layout: None },
            name.to_string(),
        )
        .expect("create node");
        doc.arena.insert(node).expect("insert")
    }

    // ── GroupNodes ─────────────────────────────────────────────────

    #[test]
    fn test_group_nodes_execute_undo_redo_cycle() {
        let mut doc = Document::new("Test".to_string());
        let parent = insert_frame(&mut doc, 1, "Parent");
        let r1 = insert_rect(&mut doc, 2, "Rect1", 10.0, 20.0, 50.0, 50.0);
        let r2 = insert_rect(&mut doc, 3, "Rect2", 100.0, 120.0, 80.0, 60.0);

        tree::add_child(&mut doc.arena, parent, r1).unwrap();
        tree::add_child(&mut doc.arena, parent, r2).unwrap();

        let cmd = GroupNodes::new(vec![r1, r2], "Group 1".to_string(), make_uuid(10))
            .expect("create cmd");

        // Execute
        doc.execute(Box::new(cmd)).expect("execute");

        // Verify group exists
        let group_id = doc.arena.id_by_uuid(&make_uuid(10)).expect("group exists");
        let group = doc.arena.get(group_id).unwrap();
        assert!(matches!(group.kind, NodeKind::Group));
        assert_eq!(group.transform.x, 10.0); // min x
        assert_eq!(group.transform.y, 20.0); // min y
        assert_eq!(group.transform.width, 170.0); // 100+80 - 10
        assert_eq!(group.transform.height, 160.0); // 120+60 - 20

        // Verify children are group-relative
        let r1_t = doc.arena.get(r1).unwrap().transform;
        assert_eq!(r1_t.x, 0.0); // 10 - 10
        assert_eq!(r1_t.y, 0.0); // 20 - 20
        let r2_t = doc.arena.get(r2).unwrap().transform;
        assert_eq!(r2_t.x, 90.0); // 100 - 10
        assert_eq!(r2_t.y, 100.0); // 120 - 20

        // Verify parent structure
        assert_eq!(doc.arena.get(r1).unwrap().parent, Some(group_id));
        assert_eq!(doc.arena.get(r2).unwrap().parent, Some(group_id));
        assert_eq!(doc.arena.get(group_id).unwrap().parent, Some(parent));

        // Undo
        doc.undo().expect("undo");

        // Group should be gone
        assert!(doc.arena.id_by_uuid(&make_uuid(10)).is_none());
        // Children restored to parent with original coords
        assert_eq!(doc.arena.get(r1).unwrap().parent, Some(parent));
        assert_eq!(doc.arena.get(r1).unwrap().transform.x, 10.0);
        assert_eq!(doc.arena.get(r1).unwrap().transform.y, 20.0);
        assert_eq!(doc.arena.get(r2).unwrap().transform.x, 100.0);
        assert_eq!(doc.arena.get(r2).unwrap().transform.y, 120.0);

        // Redo
        doc.redo().expect("redo");
        let group_id2 = doc
            .arena
            .id_by_uuid(&make_uuid(10))
            .expect("group exists after redo");
        assert!(matches!(
            doc.arena.get(group_id2).unwrap().kind,
            NodeKind::Group
        ));
        assert_eq!(doc.arena.get(r1).unwrap().transform.x, 0.0);
    }

    #[test]
    fn test_group_nodes_requires_minimum_two() {
        let r1_id = NodeId::new(1, 0);
        let result = GroupNodes::new(vec![r1_id], "Group".to_string(), make_uuid(10));
        assert!(
            result.is_err(),
            "constructor must reject fewer than MIN_GROUP_MEMBERS nodes"
        );
    }

    #[test]
    fn test_group_nodes_validates_name() {
        let result = GroupNodes::new(
            vec![NodeId::new(0, 0), NodeId::new(1, 0)],
            String::new(), // empty name
            make_uuid(10),
        );
        assert!(result.is_err());
    }

    #[test]
    fn test_group_nodes_computes_union_bounding_box() {
        let mut doc = Document::new("Test".to_string());
        let parent = insert_frame(&mut doc, 1, "Parent");
        // Node at (0, 0) with size 50x50
        let r1 = insert_rect(&mut doc, 2, "Rect1", 0.0, 0.0, 50.0, 50.0);
        // Node at (200, 300) with size 100x100
        let r2 = insert_rect(&mut doc, 3, "Rect2", 200.0, 300.0, 100.0, 100.0);

        tree::add_child(&mut doc.arena, parent, r1).unwrap();
        tree::add_child(&mut doc.arena, parent, r2).unwrap();

        let cmd =
            GroupNodes::new(vec![r1, r2], "Group".to_string(), make_uuid(10)).expect("create cmd");
        cmd.apply(&mut doc).expect("apply");

        let group_id = doc.arena.id_by_uuid(&make_uuid(10)).expect("group exists");
        let gt = doc.arena.get(group_id).unwrap().transform;
        // Union bbox: min(0, 200)=0, min(0, 300)=0, max(50, 300)=300, max(50, 400)=400
        assert_eq!(gt.x, 0.0);
        assert_eq!(gt.y, 0.0);
        assert_eq!(gt.width, 300.0); // 300 - 0
        assert_eq!(gt.height, 400.0); // 400 - 0
    }

    // RF-001: Test that undo preserves original sibling ordering
    #[test]
    fn test_group_nodes_undo_preserves_child_ordering() {
        let mut doc = Document::new("Test".to_string());
        let parent = insert_frame(&mut doc, 1, "Parent");
        let r1 = insert_rect(&mut doc, 2, "Rect1", 0.0, 0.0, 50.0, 50.0);
        let r2 = insert_rect(&mut doc, 3, "Rect2", 100.0, 0.0, 50.0, 50.0);
        let r3 = insert_rect(&mut doc, 4, "Rect3", 200.0, 0.0, 50.0, 50.0);

        tree::add_child(&mut doc.arena, parent, r1).unwrap();
        tree::add_child(&mut doc.arena, parent, r2).unwrap();
        tree::add_child(&mut doc.arena, parent, r3).unwrap();

        // Group r1 and r3 (not r2) -- r2 should remain at index 1
        let cmd =
            GroupNodes::new(vec![r1, r3], "Group".to_string(), make_uuid(10)).expect("create cmd");
        doc.execute(Box::new(cmd)).expect("execute");

        // Undo
        doc.undo().expect("undo");

        // Verify children are in original order: r1, r2, r3
        let parent_children = &doc.arena.get(parent).unwrap().children;
        assert_eq!(parent_children.len(), 3);
        assert_eq!(parent_children[0], r1);
        assert_eq!(parent_children[1], r2);
        assert_eq!(parent_children[2], r3);
    }

    // RF-020: Test that grouping parentless nodes is rejected
    #[test]
    fn test_group_nodes_rejects_parentless_nodes() {
        let mut doc = Document::new("Test".to_string());
        let r1 = insert_rect(&mut doc, 2, "Rect1", 0.0, 0.0, 50.0, 50.0);
        let r2 = insert_rect(&mut doc, 3, "Rect2", 100.0, 0.0, 50.0, 50.0);

        // r1 and r2 have no parent
        let cmd =
            GroupNodes::new(vec![r1, r2], "Group".to_string(), make_uuid(10)).expect("create cmd");
        let result = cmd.apply(&mut doc);
        assert!(result.is_err(), "grouping parentless nodes must fail");
    }

    // ── UngroupNodes ──────────────────────────────────────────────

    #[test]
    fn test_ungroup_nodes_execute_undo_redo_cycle() {
        let mut doc = Document::new("Test".to_string());
        let parent = insert_frame(&mut doc, 1, "Parent");
        let r1 = insert_rect(&mut doc, 2, "Rect1", 10.0, 20.0, 50.0, 50.0);
        let r2 = insert_rect(&mut doc, 3, "Rect2", 100.0, 120.0, 80.0, 60.0);

        tree::add_child(&mut doc.arena, parent, r1).unwrap();
        tree::add_child(&mut doc.arena, parent, r2).unwrap();

        // First, group them
        let group_cmd = GroupNodes::new(vec![r1, r2], "Group 1".to_string(), make_uuid(10))
            .expect("create group cmd");
        doc.execute(Box::new(group_cmd)).expect("group");

        let group_id = doc.arena.id_by_uuid(&make_uuid(10)).unwrap();

        // RF-003: No need to manually capture snapshots -- apply does it internally
        let ungroup_cmd =
            UngroupNodes::new(vec![group_id], vec![make_uuid(10)]).expect("create ungroup cmd");

        // Execute ungroup
        doc.execute(Box::new(ungroup_cmd)).expect("ungroup");

        // Group should be gone
        assert!(doc.arena.id_by_uuid(&make_uuid(10)).is_none());
        // Children should be back under parent with absolute coords
        assert_eq!(doc.arena.get(r1).unwrap().parent, Some(parent));
        assert_eq!(doc.arena.get(r1).unwrap().transform.x, 10.0);
        assert_eq!(doc.arena.get(r2).unwrap().transform.x, 100.0);

        // Undo -- re-creates the group
        doc.undo().expect("undo ungroup");
        let gid = doc
            .arena
            .id_by_uuid(&make_uuid(10))
            .expect("group restored");
        assert!(matches!(doc.arena.get(gid).unwrap().kind, NodeKind::Group));
        assert_eq!(doc.arena.get(r1).unwrap().parent, Some(gid));

        // Redo -- ungroups again
        doc.redo().expect("redo ungroup");
        assert!(doc.arena.id_by_uuid(&make_uuid(10)).is_none());
        assert_eq!(doc.arena.get(r1).unwrap().transform.x, 10.0);
    }

    #[test]
    fn test_ungroup_validates_target_is_group() {
        let mut doc = Document::new("Test".to_string());
        let rect = insert_rect(&mut doc, 1, "Rect", 0.0, 0.0, 50.0, 50.0);

        let cmd = UngroupNodes::new(vec![rect], vec![make_uuid(1)]).expect("create cmd");
        assert!(cmd.apply(&mut doc).is_err());
    }

    #[test]
    fn test_ungroup_empty_fails() {
        let result = UngroupNodes::new(vec![], vec![]);
        assert!(result.is_err(), "constructor must reject empty group_ids");
    }

    #[test]
    fn test_ungroup_mismatched_lengths_fails() {
        let result = UngroupNodes::new(vec![NodeId::new(0, 0)], vec![]);
        assert!(
            result.is_err(),
            "constructor must reject mismatched lengths"
        );
    }

    #[test]
    fn test_min_group_members_enforced() {
        let r1_id = NodeId::new(1, 0);
        let result = GroupNodes::new(vec![r1_id], "Group".to_string(), make_uuid(10));
        assert!(
            result.is_err(),
            "grouping fewer than MIN_GROUP_MEMBERS nodes must fail"
        );
    }

    // RF-022: Integration test chaining GroupNodes -> UngroupNodes
    #[test]
    fn test_group_then_ungroup_round_trip() {
        let mut doc = Document::new("Test".to_string());
        let parent = insert_frame(&mut doc, 1, "Parent");
        let r1 = insert_rect(&mut doc, 2, "Rect1", 10.0, 20.0, 50.0, 50.0);
        let r2 = insert_rect(&mut doc, 3, "Rect2", 100.0, 120.0, 80.0, 60.0);
        let r3 = insert_rect(&mut doc, 4, "Rect3", 200.0, 0.0, 40.0, 40.0);

        tree::add_child(&mut doc.arena, parent, r1).unwrap();
        tree::add_child(&mut doc.arena, parent, r2).unwrap();
        tree::add_child(&mut doc.arena, parent, r3).unwrap();

        // Group r1 and r2
        let group_cmd = GroupNodes::new(vec![r1, r2], "Group 1".to_string(), make_uuid(10))
            .expect("create group cmd");
        doc.execute(Box::new(group_cmd)).expect("group");

        let group_id = doc.arena.id_by_uuid(&make_uuid(10)).unwrap();

        // Ungroup
        let ungroup_cmd =
            UngroupNodes::new(vec![group_id], vec![make_uuid(10)]).expect("create ungroup cmd");
        doc.execute(Box::new(ungroup_cmd)).expect("ungroup");

        // All three rects should be under parent with original absolute coords
        assert_eq!(doc.arena.get(r1).unwrap().parent, Some(parent));
        assert_eq!(doc.arena.get(r2).unwrap().parent, Some(parent));
        assert_eq!(doc.arena.get(r3).unwrap().parent, Some(parent));
        assert_eq!(doc.arena.get(r1).unwrap().transform.x, 10.0);
        assert_eq!(doc.arena.get(r2).unwrap().transform.x, 100.0);
        assert_eq!(doc.arena.get(r3).unwrap().transform.x, 200.0);

        // Undo ungroup -- group restored
        doc.undo().expect("undo ungroup");
        let gid = doc.arena.id_by_uuid(&make_uuid(10)).unwrap();
        assert!(matches!(doc.arena.get(gid).unwrap().kind, NodeKind::Group));

        // Undo group -- everything back to original
        doc.undo().expect("undo group");
        assert!(doc.arena.id_by_uuid(&make_uuid(10)).is_none());
        let parent_children = &doc.arena.get(parent).unwrap().children;
        assert_eq!(parent_children.len(), 3);
        assert_eq!(doc.arena.get(r1).unwrap().transform.x, 10.0);
        assert_eq!(doc.arena.get(r2).unwrap().transform.x, 100.0);
        assert_eq!(doc.arena.get(r3).unwrap().transform.x, 200.0);
    }
}
