/**
 * The 200×150 SVG preview at the top of CornerSection. Renders the
 * current `Corners` value as a single <path d="..."/> generated by
 * SvgPathBuilder + Plan 14c's appendCornerPath orchestrator.
 *
 * The hotspot overlay (Task 8) renders 9 absolutely-positioned
 * <button> elements over the SVG. Buttons are revealed on :hover or
 * :focus-within (per the brainstorm decision for Plan 14d). Native
 * <button> elements provide keyboard activation (Tab + Enter/Space)
 * automatically.
 */

import type { Component } from "solid-js";
import { createMemo, createUniqueId, For, Show } from "solid-js";
import type { Corners } from "../../types/document";
import { appendCornerPath } from "../../canvas/corner-path";
import { SvgPathBuilder } from "./corner-svg-builder";
import { summarizeCornersForAria } from "./corner-aria-label";
import { ALL_HOTSPOT_IDS, type HotspotId } from "./corner-section-state";
import "./CornerPreviewSvg.css";

interface CornerPreviewSvgProps {
  /** Current corner state to render. */
  readonly corners: Corners;
  /** Optional fill color override for the preview shape. Defaults to
   *  the panel accent color set via CSS custom properties. */
  readonly fillColor?: string;
  /** Called when the user activates a hotspot (click, Enter, Space). */
  readonly onHotspotActivate: (id: HotspotId, element: HTMLButtonElement) => void;
  /** When true (uniform superellipse state), non-center hotspots are
   *  rendered disabled per the lock state in Spec 14 §1.5. */
  readonly nonCenterHotspotsDisabled?: boolean;
}

/** Logical preview dimensions. The viewBox uses these directly; the
 *  rendered size in the panel is set via CSS so the SVG scales
 *  responsively without changing the geometry. */
const PREVIEW_W = 200;
const PREVIEW_H = 150;
/** Inset on each side so corners with large radii don't clip the
 *  viewBox edge. */
const PREVIEW_INSET = 20;

/** Display label used by aria-label per hotspot. */
const HOTSPOT_ARIA: Record<HotspotId, string> = {
  tl: "Edit top-left corner",
  tr: "Edit top-right corner",
  br: "Edit bottom-right corner",
  bl: "Edit bottom-left corner",
  top: "Edit top corners",
  right: "Edit right corners",
  bottom: "Edit bottom corners",
  left: "Edit left corners",
  center: "Edit all corners",
};

/** Tooltip / title shown when non-center hotspots are locked because
 *  the four corners share a uniform superellipse shape (Spec 14 §1.5). */
const NON_CENTER_LOCKED_TITLE =
  "Superellipse applies to all corners. Change the shape to edit corners individually.";

export const CornerPreviewSvg: Component<CornerPreviewSvgProps> = (props) => {
  /**
   * Stable id for the shared lock-state description (RF-004). Generated
   * unconditionally so server-rendered output stays deterministic; the
   * sr-only span is only rendered when `nonCenterHotspotsDisabled` is
   * true, and each locked hotspot points at it via `aria-describedby`.
   */
  const lockedDescriptionId = createUniqueId();

  const pathD = createMemo(() => {
    const builder = new SvgPathBuilder();
    appendCornerPath(
      builder,
      PREVIEW_INSET,
      PREVIEW_INSET,
      PREVIEW_W - 2 * PREVIEW_INSET,
      PREVIEW_H - 2 * PREVIEW_INSET,
      props.corners,
    );
    return builder.toString();
  });

  const ariaLabel = createMemo(() => summarizeCornersForAria(props.corners));

  function handleClick(id: HotspotId, e: MouseEvent): void {
    if (props.nonCenterHotspotsDisabled && id !== "center") return;
    const target = e.currentTarget as HTMLButtonElement;
    props.onHotspotActivate(id, target);
  }

  return (
    <div class="sigil-corner-preview">
      <svg
        class="sigil-corner-preview__svg"
        viewBox={`0 0 ${PREVIEW_W} ${PREVIEW_H}`}
        role="img"
        aria-label={ariaLabel()}
      >
        <path d={pathD()} fill={props.fillColor ?? "var(--sigil-accent, #4a9eff)"} />
      </svg>
      <div class="sigil-corner-preview__hotspots">
        <For each={ALL_HOTSPOT_IDS}>
          {(id) => {
            const isLocked = (): boolean =>
              props.nonCenterHotspotsDisabled === true && id !== "center";
            return (
              <button
                type="button"
                class={`sigil-corner-preview__hotspot sigil-corner-preview__hotspot--${id}`}
                classList={{ "sigil-corner-preview__hotspot--locked": isLocked() }}
                aria-label={HOTSPOT_ARIA[id]}
                aria-disabled={isLocked() ? "true" : undefined}
                aria-describedby={isLocked() ? lockedDescriptionId : undefined}
                data-hotspot={id}
                title={isLocked() ? NON_CENTER_LOCKED_TITLE : undefined}
                onClick={(e) => handleClick(id, e)}
              />
            );
          }}
        </For>
      </div>
      {/*
       * Shared screen-reader-only explanation for locked hotspots
       * (RF-004). One span per preview; every disabled hotspot points
       * at it via aria-describedby. Rendered only while locked so AT
       * scanning the DOM doesn't surface a stale description when the
       * lock state is inactive. The visible `title` attribute remains
       * on each hotspot for sighted mouse users.
       */}
      <Show when={props.nonCenterHotspotsDisabled === true}>
        <span id={lockedDescriptionId} class="sr-only">
          {NON_CENTER_LOCKED_TITLE}
        </span>
      </Show>
    </div>
  );
};
