/**
 * The 200×150 SVG preview at the top of CornerSection. Renders the
 * current `Corners` value as a single <path d="..."/> generated by
 * SvgPathBuilder + Plan 14c's appendCornerPath orchestrator.
 *
 * The hotspot overlay (Task 8) is added as an absolutely-positioned
 * sibling inside the wrapping div.
 */

import type { Component } from "solid-js";
import { createMemo } from "solid-js";
import type { Corners } from "../../types/document";
import { appendCornerPath } from "../../canvas/corner-path";
import { SvgPathBuilder } from "./corner-svg-builder";
import { summarizeCornersForAria } from "./corner-aria-label";
import "./CornerPreviewSvg.css";

interface CornerPreviewSvgProps {
  /** Current corner state to render. */
  readonly corners: Corners;
  /** Optional fill color override for the preview shape. Defaults to
   *  the panel accent color set via CSS custom properties. */
  readonly fillColor?: string;
}

/** Logical preview dimensions. The viewBox uses these directly; the
 *  rendered size in the panel is set via CSS so the SVG scales
 *  responsively without changing the geometry. */
const PREVIEW_W = 200;
const PREVIEW_H = 150;
/** Inset on each side so corners with large radii don't clip the
 *  viewBox edge. */
const PREVIEW_INSET = 20;

export const CornerPreviewSvg: Component<CornerPreviewSvgProps> = (props) => {
  const pathD = createMemo(() => {
    const builder = new SvgPathBuilder();
    appendCornerPath(
      builder,
      PREVIEW_INSET,
      PREVIEW_INSET,
      PREVIEW_W - 2 * PREVIEW_INSET,
      PREVIEW_H - 2 * PREVIEW_INSET,
      props.corners,
    );
    return builder.toString();
  });

  const ariaLabel = createMemo(() => summarizeCornersForAria(props.corners));

  return (
    <svg
      class="sigil-corner-preview__svg"
      viewBox={`0 0 ${PREVIEW_W} ${PREVIEW_H}`}
      role="img"
      aria-label={ariaLabel()}
    >
      <path d={pathD()} fill={props.fillColor ?? "var(--sigil-accent, #4a9eff)"} />
    </svg>
  );
};
